version: 2

models:
  - name: int_zillow_city_yearly_avg
    description: >
      Intermediate table aggregating Zillow home price data for cities,
      calculating average prices for years 2010 and 2025.
      Note: 2025 data only includes 10 months of data.
    columns:
      - name: city
        description: "City name"
      
      - name: state
        description: "State abbreviation"
      
      - name: avg_home_price_2010
        description: "Average home price for the year 2010"
      
      - name: avg_home_price_2025
        description: "Average home price for the year 2025 (based on 10 months of data)"

